### PR TITLE
feat: add support for live market data

### PR DESCRIPTION
**Pull request by iamaakashbasnet**
Live market endpoint was missing. Added support for live market.

### CODE REVIEW

**Comment by iamaakashbasnet** [comment]
My vscode auto formatting did lot of changes though 😅

**Comment by basic-bgnr** [comment]
@iamaakashbasnet, thanks bro!. I'm not on my PC right now, so can't go through all the code, will check it first thing tomorrow 👍

**Comment by basic-bgnr** [comment]
@iamaakashbasnet  I just merge the dev branch containing Async feature to the master branch and ......🥁 🥁 🥁 there are some merge conflict 🙃. Hope it isn't too much of work.   

And regarding code formatting, I used `black` as my code formatter locally. I didn't add its config to `pyproject.toml` as I thought nobody would be interested in contributing  🤭. I've now added formatting config, it should work with vscode or you could just  `black .` in the project directory. 

thanks again.

**Comment by iamaakashbasnet** [comment]
@basic-bgnr 
All the conflicts are resolved. Live market endpoint returns an empty array [] when the market is closed and live market data will populate correctly when the market reopens.

**Comment by iamaakashbasnet** [comment]
Oh my bad, forgot to run it.

**Comment by iamaakashbasnet** [comment]
Screenshot from 2024-06-23 19-17-46

**Comment by basic-bgnr** [comment]
@iamaakashbasnet did you push the changes ?

**Comment by iamaakashbasnet** [comment]
I don't know why files are not getting formatted even though it says all done.
Screenshot from 2024-06-23 19-32-19

**Comment by basic-bgnr** [comment]
@iamaakashbasnet You might have other default formatter in vscode thats causing this. Try running `black .` from the system shell directly, after closing closing vs-code.
If this doesn't work, there's also a black plugin in vscode, installing that could resolve it 🤞

**Comment by iamaakashbasnet** [comment]
Did directly from the system shell plus tried the black extension too. None of the ways are working.

Screenshot from 2024-06-23 19-46-06

**Comment by basic-bgnr** [comment]
@iamaakashbasnet made a blunder. changed my black config file to write changes directly to file instead of outputing to std output. 
merge the recent change, i think it would work now

**Comment by iamaakashbasnet** [comment]
@basic-bgnr Thanks for the update. Just pushed the code formatted with the help of black.

**Pull request merged**
